# Generated by Django 3.0.4 on 2020-03-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clutch', models.CharField(max_length=20)),
                ('broods', models.CharField(max_length=20)),
                ('incubation', models.CharField(max_length=20)),
            ],
        ),
    ]
