# Generated by Django 3.0.4 on 2020-04-01 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_nest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='siting date')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('H', 'Hatchling')], default='M', max_length=1)),
                ('finch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Finch')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
