# Generated by Django 3.0.4 on 2020-04-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_siting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nest',
            name='clutch',
            field=models.CharField(max_length=20, verbose_name='clutch size'),
        ),
    ]
