# Generated by Django 3.0.4 on 2020-04-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200402_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='finch',
            options={'ordering': ['variety']},
        ),
    ]
