# Generated by Django 3.0.4 on 2020-04-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200402_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='similar',
            field=models.ManyToManyField(to='main_app.Similar'),
        ),
    ]
